// Code generated by go generate; DO NOT EDIT.
// Generated constants for collection and field names.

package entity


const (
	ColEntity = "entity"
	FEntityId = "_id"
	FEntityStatus = "status"
	FEntityCreatedAt = "created_at"
	FEntityUpdatedAt = "updated_at"
)

